WITH ALL_DATES AS (
    SELECT DISTINCT O_ORDERDATE AS DATE_COLUMN FROM {{ source('tpch_sf1', 'ORDERS') }}
    UNION
    SELECT DISTINCT L_SHIPDATE AS DATE_COLUMN FROM {{ source('tpch_sf1', 'LINEITEM') }}
    UNION
    SELECT DISTINCT L_COMMITDATE AS DATE_COLUMN FROM {{ source('tpch_sf1', 'LINEITEM') }}
    UNION
    SELECT DISTINCT L_RECEIPTDATE AS DATE_COLUMN FROM {{ source('tpch_sf1', 'LINEITEM') }}
),
-- Add a CTE to define DATE_KEY first, making it available for subsequent calculations
FINAL_DATES AS (
    SELECT
        TO_DATE(DATE_COLUMN) AS DATE_KEY,
        DATE_COLUMN -- Keep original for clarity if needed elsewhere
    FROM ALL_DATES
)
SELECT
    DATE_KEY,
    YEAR(DATE_KEY) AS CALENDAR_YEAR,
    MONTH(DATE_KEY) AS MONTH_OF_YEAR,
    DAY(DATE_KEY) AS DAY_OF_MONTH,
    DAYOFWEEK(DATE_KEY) AS DAY_OF_WEEK,
    WEEKOFYEAR(DATE_KEY) AS WEEK_OF_YEAR,
    QUARTER(DATE_KEY) AS CALENDAR_QUARTER,
    DATE_TRUNC('month', DATE_KEY) AS MONTH_START_DATE
FROM FINAL_DATES
