{{ config(materialized='table') }}

SELECT
    DD.DATE_KEY AS SALES_DATE_SK,
    COALESCE(CD.CUSTOMER_SK, -1) AS CUSTOMER_SK,
    SUM(SLF.NET_SALES_AMOUNT) AS DAILY_TOTAL_SALES_AMOUNT,
    SUM(SLF.QUANTITY_SOLD) AS DAILY_TOTAL_QUANTITY_SOLD,
    AVG(SLF.DISCOUNT_PERCENTAGE) AS DAILY_AVG_DISCOUNT_PERCENTAGE,
    COUNT(DISTINCT O.O_ORDERKEY) AS DAILY_ORDER_COUNT
FROM {{ ref('sales_lineitem_fact') }} SLF
JOIN {{ source('tpch_sf1', 'ORDERS') }} O ON SLF.ORDER_SK = MD5(O.O_ORDERKEY)
JOIN {{ ref('date_dim') }} DD ON O.O_ORDERDATE = DD.DATE_KEY
LEFT JOIN {{ ref('customer_dim') }} CD ON O.O_CUSTKEY = CD.CUSTOMER_NK
GROUP BY 1, 2