{{ config(materialized='table') }}

WITH order_lineitem_dates AS (
    SELECT
        O.O_ORDERKEY,
        O.O_CUSTKEY,
        O.O_ORDERDATE,
        O.O_TOTALPRICE,
        O.O_ORDERSTATUS,
        MIN(L.L_SHIPDATE) AS MIN_L_SHIPDATE,
        MIN(L.L_COMMITDATE) AS MIN_L_COMMITDATE,
        MAX(L.L_RECEIPTDATE) AS MAX_L_RECEIPTDATE -- Using MAX for latest receipt date for the order
    FROM {{ source('tpch_sf1', 'ORDERS') }} O
    JOIN {{ source('tpch_sf1', 'LINEITEM') }} L ON O.O_ORDERKEY = L.L_ORDERKEY
    GROUP BY 1,2,3,4,5
)
SELECT
    MD5(OLD.O_ORDERKEY) AS ORDER_SK,
    COALESCE(CD.CUSTOMER_SK, -1) AS CUSTOMER_SK,
    COALESCE(DD_ORDER.DATE_KEY, -1) AS ORDER_DATE_SK,
    COALESCE(DD_SHIP.DATE_KEY, -1) AS SHIP_DATE_SK,
    COALESCE(DD_COMMIT.DATE_KEY, -1) AS COMMIT_DATE_SK,
    COALESCE(DD_RECEIPT.DATE_KEY, -1) AS RECEIPT_DATE_SK,
    OLD.O_TOTALPRICE AS ORDER_TOTAL_AMOUNT,
    DATEDIFF('day', OLD.O_ORDERDATE, OLD.MIN_L_SHIPDATE) AS DAYS_TO_FIRST_SHIP,
    DATEDIFF('day', OLD.MIN_L_SHIPDATE, OLD.MAX_L_RECEIPTDATE) AS DAYS_SHIPPED_TO_DELIVERED,
    CASE WHEN OLD.O_ORDERSTATUS = 'F' THEN 'FULLY_DELIVERED'
            WHEN OLD.MIN_L_SHIPDATE IS NOT NULL THEN 'SHIPPED'
            ELSE 'PLACED' END AS ORDER_STATUS
FROM order_lineitem_dates OLD
LEFT JOIN {{ ref('customer_dim') }} CD ON OLD.O_CUSTKEY = CD.CUSTOMER_NK
LEFT JOIN {{ ref('date_dim') }} DD_ORDER ON OLD.O_ORDERDATE = DD_ORDER.DATE_KEY
LEFT JOIN {{ ref('date_dim') }} DD_SHIP ON OLD.MIN_L_SHIPDATE = DD_SHIP.DATE_KEY
LEFT JOIN {{ ref('date_dim') }} DD_COMMIT ON OLD.MIN_L_COMMITDATE = DD_COMMIT.DATE_KEY
LEFT JOIN {{ ref('date_dim') }} DD_RECEIPT ON OLD.MAX_L_RECEIPTDATE = DD_RECEIPT.DATE_KEY