{{ config(materialized='table') }}

SELECT
    MD5(L.L_ORDERKEY || L.L_LINENUMBER) AS LINEITEM_SK,
    MD5(L.L_ORDERKEY) AS ORDER_SK, -- Link to order-level facts/dimensions
    COALESCE(PD.PART_SK, -1) AS PART_SK,
    COALESCE(SD.SUPPLIER_SK, -1) AS SUPPLIER_SK,
    COALESCE(DD_SHIP.DATE_KEY, -1) AS SHIP_DATE_SK,
    COALESCE(DD_COMMIT.DATE_KEY, -1) AS COMMIT_DATE_SK,
    COALESCE(DD_RECEIPT.DATE_KEY, -1) AS RECEIPT_DATE_SK,
    L.L_QUANTITY AS QUANTITY_SOLD,
    L.L_EXTENDEDPRICE AS EXTENDED_PRICE,
    L.L_DISCOUNT AS DISCOUNT_PERCENTAGE,
    L.L_TAX AS TAX_PERCENTAGE,
    L.L_EXTENDEDPRICE * (1 - L.L_DISCOUNT) AS NET_SALES_AMOUNT,
    L.L_RETURNFLAG AS RETURN_FLAG,
    L.L_LINESTATUS AS LINE_STATUS,
    L.L_SHIPMODE AS SHIP_MODE,
    L.L_COMMENT AS LINEITEM_COMMENT
FROM {{ source('tpch_sf1', 'LINEITEM') }} L -- Assuming you defined tpch_sf1 as a source
LEFT JOIN {{ ref('part_dim') }} PD ON L.L_PARTKEY = PD.PART_NK
LEFT JOIN {{ ref('supplier_dim') }} SD ON L.L_SUPPKEY = SD.SUPPLIER_NK
LEFT JOIN {{ ref('date_dim') }} DD_SHIP ON L.L_SHIPDATE = DD_SHIP.DATE_KEY
LEFT JOIN {{ ref('date_dim') }} DD_COMMIT ON L.L_COMMITDATE = DD_COMMIT.DATE_KEY
LEFT JOIN {{ ref('date_dim') }} DD_RECEIPT ON L.L_RECEIPTDATE = DD_RECEIPT.DATE_KEY
